"""The overview's demo rail: every gallery example, as a light silent preview.

Pointing the rail straight at the gallery's clips was the obvious thing and the
wrong one. The first slide alone is 15 MB and the whole set 232 MB, so the band
sat blank while a narration nobody had asked for downloaded.

So each example is carried as a preview instead - silent, 4x, 720px wide, a
hundred kilobytes or so - which is how the band always worked: motion at a
glance, instantly, on any connection. The narrated clips stay in the gallery,
where an example is actually watched. A glance should not cost 232 MB.

The pipeline's own figure leads, because arriving at the demo and being shown
how AnimateBanana works, animated by AnimateBanana, is the argument the page is
making.

    python tools/build_rail_feed.py             # rebuild the feed
    python tools/build_rail_feed.py --previews  # re-encode the previews too
"""
import io
import json
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GALLERY = os.path.join(ROOT, 'data/gallery/gallery_items.json')
RAIL = os.path.join(ROOT, 'data/gallery/rail_previews.json')
PREVIEWS = 'assets/gallery/previews'
LEAD = 'pipeline_animated'
SPEED = 4            # a minute-long narrative reads as a ~15s loop
WIDTH = 720


def clock(seconds):
    s = int(round(seconds or 0))
    return '%d:%02d' % (s // 60, s % 60)


def preview(src, out):
    """A small silent loop of the clip, at SPEED times its pace."""
    os.makedirs(os.path.dirname(out), exist_ok=True)
    r = subprocess.run(
        ['ffmpeg', '-y', '-v', 'error', '-i', src,
         '-vf', 'setpts=PTS/%d,fps=25,scale=%d:-2:flags=lanczos' % (SPEED, WIDTH),
         '-an', '-c:v', 'libx264', '-preset', 'veryfast', '-crf', '30',
         '-pix_fmt', 'yuv420p', '-movflags', '+faststart', out],
        capture_output=True, text=True)
    return r.returncode == 0


def main():
    make = '--previews' in sys.argv
    gallery = json.load(io.open(GALLERY, encoding='utf-8'))
    playable = [i for i in gallery['items'] if (i.get('narrative') or {}).get('mp4')]
    lead = [i for i in playable if i['id'] == LEAD]
    rest = [i for i in playable if i['id'] != LEAD]

    items, made, bytes_ = [], 0, 0
    for it in lead + rest:
        n = it['narrative']
        rel = '%s/%s.mp4' % (PREVIEWS, it['id'])
        full = os.path.join(ROOT, rel)
        if make or not os.path.exists(full):
            ok = preview(os.path.join(ROOT, n['mp4']), full)
            made += 1 if ok else 0
            print('  %-34s %s' % (it['id'][:33],
                                  '%.0f KB' % (os.path.getsize(full) / 1024) if ok else 'FAILED'))
        if os.path.exists(full):
            bytes_ += os.path.getsize(full)
        items.append({
            'id': it['id'],
            'style': it['style'],
            'styleId': it['styleId'],
            # THE DIAGRAM, NOT THE CLIP'S FIRST FRAME. A progressive reveal
            # begins on an empty canvas, so its poster is a blank white card -
            # the band looked broken, and the example it leads with looked
            # like it was not there. The published figure says what the
            # example is before a single frame has played.
            'poster': it.get('thumb') or it.get('source') or n.get('poster'),
            'duration': clock(n.get('seconds')),
            # what autoplays: small, silent, sped up
            'sources': [{'src': rel, 'type': 'video/mp4'}] if os.path.exists(full)
                       else [{'src': n['mp4'], 'type': 'video/mp4'}],
        })

    out = {
        '_note': ("Feed for <gallery-rail> (the overview page's demo band). Generated by "
                  "tools/build_rail_feed.py from data/gallery/gallery_items.json - do not edit by "
                  "hand. Each entry points at a small silent preview under assets/gallery/previews/, "
                  "encoded at 4x so a minute-long narrative reads as a ~15s loop: the band is a "
                  "glance, and the gallery is where an example is watched at its own pace with its "
                  "narration. The pipeline's own figure leads."),
        'mediaReady': True,
        'defaultIndex': 0,
        'href': 'gallery.html',
        'items': items,
    }
    io.open(RAIL, 'w', encoding='utf-8', newline='\n').write(
        json.dumps(out, indent=1, ensure_ascii=False) + '\n')
    print('\nrail: %d examples, leading with %s' % (len(items), items[0]['id'] if items else '-'))
    print('previews: %d encoded now, %.1f MB for the set' % (made, bytes_ / 1048576))


main()
